#!/usr/bin/env ruby

require 'rundeck-ruby-client'
action, url, key, job, *exec_args = ARGV

abort "I can only execute. Other stuff may be added later." unless action.downcase == "exec"

sess = Rundeck::Session.new(url, key)
j = Rundeck::Job.find(sess, job)
encoded_args = URI::encode(exec_args.join(' '))
arg_query = encoded_args && "argString=#{encoded_args}"
puts j.execute!(arg_query).url
